stages:
  - build
  - test
  - deploy

build:
  stage: build
  script:
    - docker build -t my-app .

test:
  stage: test
  script:
    - pytest app_test.py

deploy:
  stage: deploy
  script:
    - echo "Deploying..."
